### ISSUE TITLE
Power user keybindings

### ISSUE THREAD

**Issue by kaliumxyz** [CylonicRaider/Instant#1]
Instant has some really interesting dynamics and I totally love it for chatting with my team / catching up with friends, but... It has a real lack of poweruser support, there are no functions to instantly go up a thread, or to go left/right without having to go trough a lot of text. Is it an option to either add costum bindings or to have power user functions build in?

**Comment by CylonicRaider** [comment]
Someone already proposed using PageUp/PageDown for inter-thread navigation, although this leaves the question open of how far they should move — A top-level thread? A subthread? A visual screenful?

The “official workaround” for the more fine-grained navigation is (as of 83e370981347d7f947962c08772109eb12f10da9 and following) to use Ctrl-Home/Ctrl-End to move the cursor to the very beginning/end of the input bar, and then navigate into the corresponding direction.

A reasonable and intuitive place on the keyboad for navigation controls would be the arrow keys, however, those are already heavily overloaded by the browser (for cursor movement, selection (Shift), word-granular movement (Ctrl), both (Ctrl-Shift), and even inter-page navigation (Alt)). My setup seems not to react to Alt-Shift-arrow-keys, but whether that applies to everyone else as well, or whether that's not too many modifiers, remains doubtable.

**Comment by CylonicRaider** [comment]
As far as “instantly go up/down a thread” goes, this functionality is now bound to the PageUp and PageDown keys (with invocation restrictions similar to those of Up/Down), which go to the latest message of the thread above/below the input bar position (which also can be the current thread if the input bar is not at its newest message yet). If the offscreen message alerts are present, PageUp/PageDown navigate to the messages pointed at by them instead.
