### ISSUE TITLE
Page Up makes text box jump between two positions indefinitely

### ISSUE THREAD

**Issue by Garmelon** [CylonicRaider/Instant#4]
See https://instant.leet.nu/room/welcome/#message-0005870FA3DBF000

**Comment by CylonicRaider** [comment]
A minimal set of reproduction instructions would be to:

1. Create a “passive” tab of an (empty) room and leave it alone.
2. Create another tab of the room, and produce the following message structure:

       [a message X]
         [a message Y]
           [a screenful of replies to Y]

3. Switch to the “passive” tab, and press PageUp until the input bar starts oscillating between two positions.

**Comment by CylonicRaider** [comment]
Given that both input bar positions “belong” to the same message (i.e., both would be assumed by clicking on the message repeatedly) — this is corroborated by inspecting the URL the offscreen notification arrow points to —, the probable cause is that the message's ‘offscreen’ status is not cleared, and it is hence selected over and over.
